### USUÁRIO - CONSULTAR

GET http://localhost:8080/usuario/consultar HTTP/1.1

### USUÁRIO - GRAVAR

POST http://localhost:8080/usuario/gravar HTTP/1.1
content-type: application/json

{
    "nomeCompleto": "Walter Sobchak",
    "sexo": "Masculino",
    "endereco": "Rua WS",
    "dataNascimento": "1983-03-01",
    "login": "walter",
    "senha": "123"

}

### USUÁRIO - ALTERAR

POST http://localhost:8080/usuario/alterar/2 HTTP/1.1
content-type: application/json

{
    "senha": "012345"

}

### USUÁRIO - EXCLUIR

POST http://localhost:8080/usuario/excluir/1 HTTP/1.1
content-type: application/json

### EVENTO - CONSULTAR

GET http://localhost:8080/evento/consultar HTTP/1.1

### EVENTO - GRAVAR

POST http://localhost:8080/evento/gravar HTTP/1.1
content-type: application/json

{
    "nome": "Evento de teste",
    "descricao": "Teste de requisições e de banco dados",
    "dataInicio": "2021-02-28",
    "dataFim": "2021-03-06"

}

### EVENTO - ALTERAR

POST http://localhost:8080/evento/alterar/2 HTTP/1.1
content-type: application/json

{
    "localEvento": "FeMASS"

}

### EVENTO - EXCLUIR

POST http://localhost:8080/evento/excluir/1 HTTP/1.1
content-type: application/json

### GRUPO - CONSULTAR

GET http://localhost:8080/grupo/consultar HTTP/1.1

### GRUPO - GRAVAR

POST http://localhost:8080/grupo/gravar HTTP/1.1
content-type: application/json

{
    "nome": "Grupo 3",
    "descricao": "Grupo de planejamento",
    "dataRenovacao": "2021-07-27"

}

### GRUPO - ALTERAR

POST http://localhost:8080/grupo/alterar HTTP/1.1
content-type: application/json

{
    "id": 18,
    "descricao": "Grupo de testes",
    "dataRenovacao": "2021-09-08",
    "nome": "Grupo 333"

}

### GRUPO - EXCLUIR

POST http://localhost:8080/grupo/excluir/1 HTTP/1.1
content-type: application/json

### GRUPO - ADICIONAR MEMBRO

POST http://localhost:8080/grupo/gerenciar/17/membros/adicionar/4 HTTP/1.1
content-type: application/json

### GRUPO - REMOVER MEMBRO

POST http://localhost:8080/grupo/gerenciar/1/membros/remover/2 HTTP/1.1
content-type: application/json

### GRUPO - ESVAZIAR GRUPO

POST http://localhost:8080/grupo/gerenciar/1/membros/esvaziar HTTP/1.1
content-type: application/json

### GRUPO - ESCOLHER LÍDER

POST http://localhost:8080/grupo/gerenciar/1/membros/lider/2 HTTP/1.1
content-type: application/json

### GRUPO - LISTAR MEMBROS

POST http://localhost:8080/grupo/gerenciar/17/listar HTTP/1.1
content-type: application/json
