### USUÁRIO - LOGIN VISUALIZAR
GET http://localhost:8090/usuario/login/visualizar HTTP/1.1

### USUÁRIO - LOGAR
GET http://localhost:8090/usuario/login/nathalia/123 HTTP/1.1

### USUÁRIO - CONSULTAR

GET http://localhost:8090/usuario/consultar HTTP/1.1

### USUÁRIO - GRAVAR

POST http://localhost:8090/usuario/gravar HTTP/1.1
content-type: application/json

{
    "nomeCompleto": "Nathalia Galante",
    "sexo": "Feminino",
    "endereco": "Rua NG",
    "dataNascimento": "1998-01-02",
    "login": "nathalia",
    "senha": "123"

}

### USUÁRIO - ALTERAR

POST http://localhost:8090/usuario/alterar/2 HTTP/1.1
content-type: application/json

{
    "senha": "012345"

}

### USUÁRIO - EXCLUIR

POST http://localhost:8090/usuario/excluir/1 HTTP/1.1
content-type: application/json

### EVENTO - CONSULTAR

GET http://localhost:8090/evento/consultar HTTP/1.1

### EVENTO - GRAVAR

POST http://localhost:8090/evento/gravar HTTP/1.1
content-type: application/json

{
    "nome": "Evento teste 4",
    "descricao": "Teste 4",
    "dataInicio": "2021-05-05",
    "dataFim": "2021-05-08",
    "localEvento": "Rua 5, Avenida ET4"

}

### EVENTO - ALTERAR

POST http://localhost:8090/evento/alterar/7 HTTP/1.1
content-type: application/json

{
    "localEvento": "FeMASS",
    "publicoAlvo": "Desenvolvedores"

}

### EVENTO - EXCLUIR

POST http://localhost:8090/evento/excluir/1 HTTP/1.1
content-type: application/json

### EVENTO - ANIVERSÁRIOS

POST http://localhost:8090/evento/aniversarios/2021 HTTP/1.1
content-type: application/json

### GRUPO - CONSULTAR

GET http://localhost:8090/grupo/consultar HTTP/1.1

### GRUPO - GRAVAR

POST http://localhost:8090/grupo/gravar HTTP/1.1
content-type: application/json

{
    "nome": "Grupo 3",
    "descricao": "Grupo de planejamento",
    "dataRenovacao": "2021-07-27"

}

### GRUPO - ALTERAR

POST http://localhost:8090/grupo/alterar HTTP/1.1
content-type: application/json

{
    "id": 18,
    "descricao": "Grupo de testes",
    "dataRenovacao": "2021-09-08",
    "nome": "Grupo 333"

}

### GRUPO - EXCLUIR

POST http://localhost:8090/grupo/excluir/17 HTTP/1.1
content-type: application/json

### GRUPO - ADICIONAR MEMBRO

POST http://localhost:8090/grupo/gerenciar/28/membros/adicionar/8 HTTP/1.1
content-type: application/json

### GRUPO - REMOVER MEMBRO

POST http://localhost:8090/grupo/gerenciar/17/membros/remover/4 HTTP/1.1
content-type: application/json

### GRUPO - ESVAZIAR GRUPO

POST http://localhost:8090/grupo/gerenciar/25/membros/esvaziar HTTP/1.1
content-type: application/json

### GRUPO - ESCOLHER LÍDER

POST http://localhost:8090/grupo/gerenciar/29/membros/lider/5 HTTP/1.1
content-type: application/json

### GRUPO - LISTAR MEMBROS

GET http://localhost:8090/grupo/gerenciar/29/listar HTTP/1.1
content-type: application/json

### GRUPO - LISTAR USUÁRIOS SEM GRUPO

GET http://localhost:8090/grupo/gerenciar/listargroupless HTTP/1.1
content-type: application/json
